/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LineItemResult = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Text,
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Text,
});
export const Address = IDL.Record({
  'postcode' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'address1' : IDL.Text,
  'address2' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const WooOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerNote' : IDL.Text,
  'status' : IDL.Text,
  'lineItems' : IDL.Vec(LineItemResult),
  'total' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'dateCreated' : IDL.Text,
  'shipping' : Address,
  'billing' : Address,
});
export const Result_7 = IDL.Variant({ 'ok' : WooOrder, 'err' : IDL.Text });
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const LineItem = IDL.Record({
  'productId' : IDL.Nat,
  'variationId' : IDL.Opt(IDL.Nat),
  'quantity' : IDL.Nat,
});
export const CouponLine = IDL.Record({ 'code' : IDL.Text });
export const OrderData = IDL.Record({
  'customerNote' : IDL.Text,
  'lineItems' : IDL.Vec(LineItem),
  'paymentMethod' : IDL.Text,
  'shipping' : Address,
  'billing' : Address,
  'couponLines' : IDL.Vec(CouponLine),
  'customerId' : IDL.Opt(IDL.Nat),
});
export const WooCustomer = IDL.Record({
  'id' : IDL.Nat,
  'shipping' : Address,
  'billing' : Address,
  'email' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : WooCustomer, 'err' : IDL.Text });
export const CategoryImage = IDL.Record({ 'alt' : IDL.Text, 'src' : IDL.Text });
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'count' : IDL.Nat,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(CategoryImage),
  'parentId' : IDL.Nat,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(Category),
  'err' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(WooOrder),
  'err' : IDL.Text,
});
export const ProductCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
});
export const ProductAttribute = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const ProductImage = IDL.Record({
  'id' : IDL.Nat,
  'alt' : IDL.Text,
  'src' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categories' : IDL.Vec(ProductCategory),
  'stockStatus' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'shortDescription' : IDL.Text,
  'attributes' : IDL.Vec(ProductAttribute),
  'salePrice' : IDL.Text,
  'regularPrice' : IDL.Text,
  'price' : IDL.Text,
  'variations' : IDL.Vec(IDL.Nat),
  'images' : IDL.Vec(ProductImage),
});
export const Result_5 = IDL.Variant({ 'ok' : Product, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(Product),
  'err' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Vec(IDL.Nat),
  'err' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const CustomerUpdateData = IDL.Record({
  'shipping' : IDL.Opt(Address),
  'billing' : IDL.Opt(Address),
  'email' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Opt(IDL.Text),
  'firstName' : IDL.Opt(IDL.Text),
});
export const Coupon = IDL.Record({
  'code' : IDL.Text,
  'discountType' : IDL.Text,
  'minimumAmount' : IDL.Text,
  'amount' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [Result_2], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [Result_7], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([OrderData], [Result_7], []),
  'createWooCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [Result_8], []),
  'getOrder' : IDL.Func([IDL.Nat], [Result_7], []),
  'getOrders' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [Result_6], []),
  'getProduct' : IDL.Func([IDL.Nat], [Result_5], []),
  'getProducts' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [Result_4],
      [],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getWishlist' : IDL.Func([], [Result_3], ['query']),
  'getWooCustomer' : IDL.Func([IDL.Nat], [Result_1], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [Result_2], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateWooCustomer' : IDL.Func([IDL.Nat, CustomerUpdateData], [Result_1], []),
  'validateCoupon' : IDL.Func([IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LineItemResult = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Text,
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Text,
  });
  const Address = IDL.Record({
    'postcode' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'address1' : IDL.Text,
    'address2' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const WooOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerNote' : IDL.Text,
    'status' : IDL.Text,
    'lineItems' : IDL.Vec(LineItemResult),
    'total' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'dateCreated' : IDL.Text,
    'shipping' : Address,
    'billing' : Address,
  });
  const Result_7 = IDL.Variant({ 'ok' : WooOrder, 'err' : IDL.Text });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const LineItem = IDL.Record({
    'productId' : IDL.Nat,
    'variationId' : IDL.Opt(IDL.Nat),
    'quantity' : IDL.Nat,
  });
  const CouponLine = IDL.Record({ 'code' : IDL.Text });
  const OrderData = IDL.Record({
    'customerNote' : IDL.Text,
    'lineItems' : IDL.Vec(LineItem),
    'paymentMethod' : IDL.Text,
    'shipping' : Address,
    'billing' : Address,
    'couponLines' : IDL.Vec(CouponLine),
    'customerId' : IDL.Opt(IDL.Nat),
  });
  const WooCustomer = IDL.Record({
    'id' : IDL.Nat,
    'shipping' : Address,
    'billing' : Address,
    'email' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : WooCustomer, 'err' : IDL.Text });
  const CategoryImage = IDL.Record({ 'alt' : IDL.Text, 'src' : IDL.Text });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'count' : IDL.Nat,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(CategoryImage),
    'parentId' : IDL.Nat,
  });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Vec(Category), 'err' : IDL.Text });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Vec(WooOrder), 'err' : IDL.Text });
  const ProductCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
  });
  const ProductAttribute = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const ProductImage = IDL.Record({
    'id' : IDL.Nat,
    'alt' : IDL.Text,
    'src' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categories' : IDL.Vec(ProductCategory),
    'stockStatus' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'shortDescription' : IDL.Text,
    'attributes' : IDL.Vec(ProductAttribute),
    'salePrice' : IDL.Text,
    'regularPrice' : IDL.Text,
    'price' : IDL.Text,
    'variations' : IDL.Vec(IDL.Nat),
    'images' : IDL.Vec(ProductImage),
  });
  const Result_5 = IDL.Variant({ 'ok' : Product, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Vec(Product), 'err' : IDL.Text });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Vec(IDL.Nat), 'err' : IDL.Text });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const CustomerUpdateData = IDL.Record({
    'shipping' : IDL.Opt(Address),
    'billing' : IDL.Opt(Address),
    'email' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Opt(IDL.Text),
    'firstName' : IDL.Opt(IDL.Text),
  });
  const Coupon = IDL.Record({
    'code' : IDL.Text,
    'discountType' : IDL.Text,
    'minimumAmount' : IDL.Text,
    'amount' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : Coupon, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [Result_2], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [Result_7], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([OrderData], [Result_7], []),
    'createWooCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [Result_8], []),
    'getOrder' : IDL.Func([IDL.Nat], [Result_7], []),
    'getOrders' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [Result_6], []),
    'getProduct' : IDL.Func([IDL.Nat], [Result_5], []),
    'getProducts' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [Result_4],
        [],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getWishlist' : IDL.Func([], [Result_3], ['query']),
    'getWooCustomer' : IDL.Func([IDL.Nat], [Result_1], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [Result_2], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateWooCustomer' : IDL.Func(
        [IDL.Nat, CustomerUpdateData],
        [Result_1],
        [],
      ),
    'validateCoupon' : IDL.Func([IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };