/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'postcode' : string,
  'country' : string,
  'city' : string,
  'email' : string,
  'company' : string,
  'state' : string,
  'phone' : string,
  'address1' : string,
  'address2' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface Category {
  'id' : bigint,
  'name' : string,
  'count' : bigint,
  'slug' : string,
  'description' : string,
  'image' : [] | [CategoryImage],
  'parentId' : bigint,
}
export interface CategoryImage { 'alt' : string, 'src' : string }
export interface Coupon {
  'code' : string,
  'discountType' : string,
  'minimumAmount' : string,
  'amount' : string,
}
export interface CouponLine { 'code' : string }
export interface CustomerUpdateData {
  'shipping' : [] | [Address],
  'billing' : [] | [Address],
  'email' : [] | [string],
  'lastName' : [] | [string],
  'firstName' : [] | [string],
}
export interface LineItem {
  'productId' : bigint,
  'variationId' : [] | [bigint],
  'quantity' : bigint,
}
export interface LineItemResult {
  'id' : bigint,
  'total' : string,
  'name' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'price' : string,
}
export interface OrderData {
  'customerNote' : string,
  'lineItems' : Array<LineItem>,
  'paymentMethod' : string,
  'shipping' : Address,
  'billing' : Address,
  'couponLines' : Array<CouponLine>,
  'customerId' : [] | [bigint],
}
export interface Product {
  'id' : bigint,
  'categories' : Array<ProductCategory>,
  'stockStatus' : string,
  'name' : string,
  'slug' : string,
  'description' : string,
  'shortDescription' : string,
  'attributes' : Array<ProductAttribute>,
  'salePrice' : string,
  'regularPrice' : string,
  'price' : string,
  'variations' : Array<bigint>,
  'images' : Array<ProductImage>,
}
export interface ProductAttribute {
  'id' : bigint,
  'name' : string,
  'options' : Array<string>,
}
export interface ProductCategory {
  'id' : bigint,
  'name' : string,
  'slug' : string,
}
export interface ProductImage { 'id' : bigint, 'alt' : string, 'src' : string }
export type Result = { 'ok' : Coupon } |
  { 'err' : string };
export type Result_1 = { 'ok' : WooCustomer } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type Result_3 = { 'ok' : Array<bigint> } |
  { 'err' : string };
export type Result_4 = { 'ok' : Array<Product> } |
  { 'err' : string };
export type Result_5 = { 'ok' : Product } |
  { 'err' : string };
export type Result_6 = { 'ok' : Array<WooOrder> } |
  { 'err' : string };
export type Result_7 = { 'ok' : WooOrder } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<Category> } |
  { 'err' : string };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WooCustomer {
  'id' : bigint,
  'shipping' : Address,
  'billing' : Address,
  'email' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface WooOrder {
  'id' : bigint,
  'customerNote' : string,
  'status' : string,
  'lineItems' : Array<LineItemResult>,
  'total' : string,
  'paymentMethod' : string,
  'dateCreated' : string,
  'shipping' : Address,
  'billing' : Address,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addToWishlist' : ActorMethod<[bigint], Result_2>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[bigint], Result_7>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[OrderData], Result_7>,
  'createWooCustomer' : ActorMethod<[string, string, string, string], Result_1>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Result_8>,
  'getOrder' : ActorMethod<[bigint], Result_7>,
  'getOrders' : ActorMethod<[bigint, bigint, bigint], Result_6>,
  'getProduct' : ActorMethod<[bigint], Result_5>,
  'getProducts' : ActorMethod<
    [bigint, bigint, [] | [bigint], [] | [string], string, string],
    Result_4
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getWishlist' : ActorMethod<[], Result_3>,
  'getWooCustomer' : ActorMethod<[bigint], Result_1>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromWishlist' : ActorMethod<[bigint], Result_2>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateWooCustomer' : ActorMethod<[bigint, CustomerUpdateData], Result_1>,
  'validateCoupon' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];